### GET ALL local type

GET http://{{host}}:{{port}}/local-type
Accept: application/json

### GET A local type

GET http://{{host}}:{{port}}/local-type/1
Accept: application/json
X-Systema-Auth: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbklkIjoiYTg3ZmY2NzlhMmYzZTcxZGE2OTc3YzJhOThlYjdiZDAiLCJsb2dpbklkIjo0LCJlbWFpbCI6InBpcHBvQGNpY2Npby5jb20iLCJhY2Nlc3MiOiIyMDIwLTAzLTIyIDEwOjM3OjEzIn0.RIW5uh5KTVTBgknbmpeoaSdrQYtgcyJbvj3Go2jG8bE

### GET All Roles
GET http://{{host}}:{{port}}/role
Accept: application/json

### GET Single Role
GET http://{{host}}:{{port}}/role/1
Accept: application/json

### POST login
POST http://{{host}}:{{port}}/login
Accept: application/json
Content-Type: application/json

{
  "email": "pippo@ciccio.com",
  "password": "testtest123"
}

### POST Autenticazione
POST http://{{host}}:{{port}}/session
Accept: application/json
Content-Type: application/json

{
  "email": "pippo@ciccio.com",
  "password": "testtest123"
}

### GET session

GET http://{{host}}:{{port}}/session/a87ff679a2f3e71d2f4ca6d6552a1f91
Accept: application/json
X-Systema-Auth: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbklkIjoiYTg3ZmY2NzlhMmYzZTcxZDJmNGNhNmQ2NTUyYTFmOTEiLCJsb2dpbklkIjo0LCJlbWFpbCI6InBpcHBvQGNpY2Npby5jb20iLCJhY2Nlc3MiOiIyMDIwLTAzLTIxIDE1OjQxOjQyIiwiZXhwaXJlIjoiMjAyMC0wMy0yMSAxNjo0MTo0MiJ9.k5FTcbQNkcwZFXKaTDVNYd661pHsSzSh0ytGjfcR1ag

### Update Session

PUT http://{{host}}:{{port}}/session/a87ff679a2f3e71d7ce7a25a0bb41630
Accept: application/json
Content-Type: application/json
X-Systema-Auth: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbklkIjoiYTg3ZmY2NzlhMmYzZTcxZDdjZTdhMjVhMGJiNDE2MzAiLCJsb2dpbklkIjo0LCJlbWFpbCI6InBpcHBvQGNpY2Npby5jb20iLCJhY2Nlc3MiOiIyMDIwLTAzLTIxIDE4OjExOjU0In0.9Rebu2vqdkoMwDe1YOIcBGO_KTpJy1W8RkAg0UZcWqI

{
  "email": "empty@email.com",
  "password": "password"
}

###


