### GET ALL local type

GET http://{{host}}:{{port}}/local-type
Accept: application/json

### GET A local type

GET http://{{host}}:{{port}}/local-type/1
Accept: application/json

### GET All Roles
GET http://{{host}}:{{port}}/role
Accept: application/json

### GET Single Role
GET http://{{host}}:{{port}}/role/1
Accept: application/json

### POST login
POST http://{{host}}:{{port}}/login
Accept: application/json
Content-Type: application/json

{
  "email": "pippo@ciccio.com",
  "password": "testtest123"
}

###

